### ISSUE TITLE
PHP8.1 upgrade-error: Array and string offset access syntax with curly braces is no longer supported

### ISSUE THREAD

**Issue by schnackOpPlatt** [cosmocode/dokuwiki-plugin-tplinc#3]
**<dw-dir>/data/log/error - LOG:**

<dw-dir>/lib/plugins/tplinc/helper.php(148) **->** dokuwiki\Exception\FatalException: **->** Array and string offset access syntax with curly braces is no longer supported

  0 [internal function]: dokuwiki\ErrorHandler::fatalShutdown()
  1 {main}

----
https://stackoverflow.com/questions/59158548/array-and-string-offset-access-syntax-with-curly-braces-is-deprecated/59158549#59158549

**Comment by splitbrain** [comment]
fixed in 99c631ebba514c417dc6341f4e64a2243709b086
